# Default resource configuration for bioagents
# This can be overridden for different deployments

compute:
  cpu:
    cores: 30  # Default conservative estimate
    memory_gb: 220  # Default memory in GB
  gpu:
    available: true  # Whether GPU is available
    type: "A10"  # GPU type (e.g., "A10", "V100", "T4")
    memory_gb: 24  # GPU memory in GB
    count: 1  # Number of GPUs
  
timeout:
  docker_execution: 3600  # Default 1 hour timeout for docker 