# @package _global_
# Default Docker configuration

# Docker executor settings
docker:
  image: millerh1/bioagents:latest
  timeout: 3600
  work_dir: ${hydra:runtime.cwd}
  
# GPU configuration
gpus: "all"  # "all", "none", or comma-separated indices like "0,1,2"

# Docker device requests
device_requests:
  gpu_enabled: true
  capabilities: [["gpu"]] 