# @package _global_
# Default Docker configuration

# Docker executor settings
docker:
  image: millerh1/autobioml:latest
  timeout: 1800  # 30 minutes
  work_dir: ${hydra:runtime.output_dir}
  
# GPU configuration
gpus: "all"  # "all", "none", or comma-separated indices like "0,1,2"

# Docker device requests
device_requests:
  gpu_enabled: true
  capabilities: [["gpu"]] 